# Generated by Django 5.2 on 2025-07-16 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('mobile_num', models.IntegerField()),
                ('address', models.TextField()),
                ('designation', models.CharField(choices=[('YD', 'Your designation'), ('CE', 'Cloud Engineer'), ('DQM', 'Data Quality Manager'), ('DS', 'Data Science'), ('DA', 'Database Administrator'), ('ISS', 'IT Security Specialist'), ('AE', 'Applications Engineer'), ('O', 'Other')], default='YD', max_length=20)),
                ('employe_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('working', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('G', 'Gender'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='G', max_length=1)),
                ('email_id', models.EmailField(max_length=100)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
